site_name: Documentação do Sistema Sigworks
theme:
  name: ivory
  language: pt
extra_css:
  - styles/extra.css
nav:
  - Home: index.md
  - Versões:
      - v1.57:
          - Visão Geral: versions/v1.57/index.md
          - Changelog: versions/v1.57/changelog.md
  - Módulos:
      - Historico de Versões:
          - Manual de uso: modules/historico_versoes/index.md
plugins:
  - search